# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  # Test Host 1
  config.vm.define "dev1" do |dev1|
    dev1.vm.hostname = "dev1"
    dev1.vm.box = "ubuntu1804"
    dev1.vm.box_url = "file://ubuntu1804.box"
    dev1.vm.synced_folder ".", "/vagrant", disabled: true
    dev1.vm.network "forwarded_port", guest: 80, host: 8000
    dev1.vm.provider "virtualbox" do |vb|
      vb.name = "dev1"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--vrde", "off"]
      vb.customize ["modifyvm", :id, "--vram", "12"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]      
    end
    # Do your other provisioning here ...
    # dev1.vm.provision :shell, path: "bootstrap.sh"
    # dev1.vm.provision "ansible" do |ansible|
    # ansible.playbook = "provisioning/site.yml"
    # ansible.host_key_checking = false
    # ansible.raw_ssh_args = '-o PasswordAuthentication=no -o IdentitiesOnly=yes'  # ... etc 
    # end
  end

  # Test Host 2
  # config.vm.define "dev2" do |dev2|
  #  dev2.vm.hostname = "dev2"
  # ... etc

  # Test Host 3
  # ... etc

end
